services:
  text-models:
    build: .
    container_name: text-models
    image: text-models
    volumes:
      - .:/usr/src/develop
    network_mode: host
    #ports:
    #  - 8888:8888
    tty: true
    command: ["bash"]
